communicator_node:
  ros__parameters:
    model_api_url: https://ea5i5e07fh1w-s8tvic3pz6qy.serving.hyperai.host
    prompt: "Move to the monitor, stop in front of it, and avoid any collisions"
    image_topic: /image_rect/compressed
    waypoints_topic: /waypoints
    model_api_health_check: true
    model_api_timeout_sec: 600

